name: Superkart Project Pipeline

on:
  workflow_dispatch:

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r Files/deployment/requirements.txt

      - name: Register dataset on Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Files/model/register_data.py


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r Files/deployment/requirements.txt

      - name: Run data preparation
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Files/model/preparation.py


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r Files/deployment/requirements.txt

      - name: Train and register model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Files/model/train.py


  deploy-hosting:
    needs: model-training
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r Files/deployment/requirements.txt

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python Files/hosting/hosting.py
